apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: please-delete
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: please-delete
    spec:
      containers:
        - name: please-delete
          image: registry.gitlab.com/hari87/please-delete
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: registry.gitlab.com
