spec:
  template:
    spec:
      containers:
        - env:
          - name: JAVA_APP_DIR
            value: /deployments
          - name: JAVA_OPTIONS
            value: -Dspring.profiles.active=prod
          volumeMounts:
          - name: application-config 
            mountPath: "/deployments/config" 
            readOnly: true
      volumes:
      - name: application-config
        configMap:
          name: spring-app-config 
          items:
          - key: application.yml
            path: application.yml
