server:
  port: 8080
management:
  endpoint:
    camelroutecontroller:
      enabled: true
    restart:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: never
      enabled: true
    info:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

datasource:
  name: test-YAML
  sample: anotherDataa
